#!/bin/bash
#PBS -l nodes=4:ppn=8,walltime=2:00:00
cd $PBS_O_WORKDIR
NPP=`wc -l $PBS_NODEFILE | awk '{print $1}' `
cat $PBS_NODEFILE | sort | uniq
cat $PBS_NODEFILE > machine.ib
sort -u machine.ib > machine.ibs
#sort -u machine.ib >> machine.ibs
#export DISPLAY=claur342.der.edf.fr
export ILOG_LICENSE_FILE=/logiciels/Cplex/ilog/ilm/access_1.ilm
export LD_LIBRARY_PATH=LD_LIBRARY_PATH:/home/logiciels/intel/Compiler/11.1/046/lib/intel64
/logiciels/openmpi_intel/bin/mpirun -n 32 -npernode 8 -machinefile machine.ib /home/doukopou/Tests/Executables/apogene-afARC-parusi
